version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_backend_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patients_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend_api
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/patients_db
      - PORT=5000
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    ports:
      - "5173:80"
    depends_on:
      - backend


volumes:
  postgres_data: